/* ===== TypeHub — بانک محتوای آموزشی =====
   سطوح: 0 الفبا → 1 کلمات ساده → 2 جمله خیلی ساده → 3 مکالمه A1 → 4 روزمره A2 → 5 داستان B1
   هر آیتم: { en, fa, topic, w? } — w آرایه [انگلیسی، فارسی] برای معنی کلمه‌به‌کلمه
*/
const LEVELS = [
{
  id: 0, name: "سطح صفر: الفبا", icon: "🔤",
  desc: "اسم حرف‌ها رو گوش بده و همون حرف رو تایپ کن. پایه‌ی همه‌چیز!",
  tip: "نکته: اسم هر حرف رو بلند تکرار کن؛ برای هجی کردن اسم و ایمیلت لازمش داری.",
  kind: "letter",
  items: [
    {en:"A",fa:"اِی"},{en:"B",fa:"بی"},{en:"C",fa:"سی"},{en:"D",fa:"دی"},
    {en:"E",fa:"ای"},{en:"F",fa:"اِف"},{en:"G",fa:"جی"},{en:"H",fa:"اِیچ"},
    {en:"I",fa:"آی"},{en:"J",fa:"جِی"},{en:"K",fa:"کِی"},{en:"L",fa:"اِل"},
    {en:"M",fa:"اِم"},{en:"N",fa:"اِن"},{en:"O",fa:"اُو"},{en:"P",fa:"پی"},
    {en:"Q",fa:"کیو"},{en:"R",fa:"آر"},{en:"S",fa:"اِس"},{en:"T",fa:"تی"},
    {en:"U",fa:"یو"},{en:"V",fa:"وی"},{en:"W",fa:"دابلیو"},{en:"X",fa:"اِکس"},
    {en:"Y",fa:"وای"},{en:"Z",fa:"زِد"}
  ]
},
{
  id: 1, name: "سطح ۱: کلمات ساده", icon: "🍎",
  desc: "کلمات کوتاه و پرکاربرد رو گوش بده و تایپ کن + معنیشون رو یاد بگیر.",
  tip: "نکته: تکیه بیشتر کلمات روی بخش اوله: TA-ble — با صدا تقلید کن.",
  kind: "word",
  items: [
    {en:"cat",fa:"گربه",topic:"حیوانات"},{en:"dog",fa:"سگ",topic:"حیوانات"},
    {en:"bird",fa:"پرنده",topic:"حیوانات"},{en:"fish",fa:"ماهی",topic:"حیوانات"},
    {en:"sun",fa:"خورشید",topic:"طبیعت"},{en:"moon",fa:"ماه",topic:"طبیعت"},
    {en:"star",fa:"ستاره",topic:"طبیعت"},{en:"rain",fa:"باران",topic:"طبیعت"},
    {en:"book",fa:"کتاب",topic:"مدرسه"},{en:"pen",fa:"خودکار",topic:"مدرسه"},
    {en:"school",fa:"مدرسه",topic:"مدرسه"},{en:"teacher",fa:"معلم",topic:"مدرسه"},
    {en:"apple",fa:"سیب",topic:"غذا"},{en:"bread",fa:"نان",topic:"غذا"},
    {en:"water",fa:"آب",topic:"غذا"},{en:"milk",fa:"شیر",topic:"غذا"},
    {en:"house",fa:"خانه",topic:"خانه"},{en:"door",fa:"در",topic:"خانه"},
    {en:"table",fa:"میز",topic:"خانه"},{en:"chair",fa:"صندلی",topic:"خانه"},
    {en:"mother",fa:"مادر",topic:"خانواده"},{en:"father",fa:"پدر",topic:"خانواده"},
    {en:"sister",fa:"خواهر",topic:"خانواده"},{en:"brother",fa:"برادر",topic:"خانواده"},
    {en:"red",fa:"قرمز",topic:"رنگ‌ها"},{en:"blue",fa:"آبی",topic:"رنگ‌ها"},
    {en:"green",fa:"سبز",topic:"رنگ‌ها"},{en:"yellow",fa:"زرد",topic:"رنگ‌ها"},
    {en:"one",fa:"یک",topic:"اعداد"},{en:"two",fa:"دو",topic:"اعداد"},
    {en:"three",fa:"سه",topic:"اعداد"},{en:"ten",fa:"ده",topic:"اعداد"},
    {en:"day",fa:"روز",topic:"زمان"},{en:"night",fa:"شب",topic:"زمان"},
    {en:"morning",fa:"صبح",topic:"زمان"},{en:"today",fa:"امروز",topic:"زمان"},
    {en:"happy",fa:"خوشحال",topic:"احساسات"},{en:"sad",fa:"ناراحت",topic:"احساسات"},
    {en:"big",fa:"بزرگ",topic:"صفت‌ها"},{en:"small",fa:"کوچک",topic:"صفت‌ها"},
    {en:"good",fa:"خوب",topic:"صفت‌ها"},{en:"new",fa:"جدید",topic:"صفت‌ها"},
    {en:"run",fa:"دویدن",topic:"فعل‌ها"},{en:"eat",fa:"خوردن",topic:"فعل‌ها"},
    {en:"drink",fa:"نوشیدن",topic:"فعل‌ها"},{en:"sleep",fa:"خوابیدن",topic:"فعل‌ها"},
    {en:"love",fa:"دوست داشتن",topic:"فعل‌ها"},{en:"like",fa:"دوست داشتن",topic:"فعل‌ها"},
    {en:"go",fa:"رفتن",topic:"فعل‌ها"},{en:"come",fa:"آمدن",topic:"فعل‌ها"},
    {en:"Sara",fa:"سارا — تمرین هجی اسم",topic:"هجی"},{en:"Ali",fa:"علی — تمرین هجی اسم",topic:"هجی"},
    {en:"Reza",fa:"رضا — تمرین هجی اسم",topic:"هجی"},{en:"Maryam",fa:"مریم — تمرین هجی اسم",topic:"هجی"},
    {en:"Tehran",fa:"تهران — تمرین هجی",topic:"هجی"},{en:"Iran",fa:"ایران — تمرین هجی",topic:"هجی"},
    {en:"Shiraz",fa:"شیراز — تمرین هجی",topic:"هجی"},{en:"Persian",fa:"فارسی — تمرین هجی",topic:"هجی"}
  ]
},
{
  id: 2, name: "سطح ۲: جمله‌های خیلی ساده", icon: "💬",
  desc: "اولین جمله‌های انگلیسی‌ات! کوتاه، ساده و پرکاربرد.",
  tip: "نکته: a/an یعنی «یک»: a cat. و the یعنی همونِ مشخص: the cat.",
  kind: "sentence",
  items: [
    {en:"I am Ali.", fa:"من علی هستم.", topic:"معرفی",
     w:[["I","من"],["am","هستم"],["Ali","علی"]]},
    {en:"I am happy.", fa:"من خوشحالم.", topic:"معرفی",
     w:[["I","من"],["am","هستم"],["happy","خوشحال"]]},
    {en:"This is a cat.", fa:"این یک گربه است.", topic:"معرفی",
     w:[["This","این"],["is","است"],["a","یک"],["cat","گربه"]]},
    {en:"That is a dog.", fa:"آن یک سگ است.", topic:"معرفی",
     w:[["That","آن"],["is","است"],["a","یک"],["dog","سگ"]]},
    {en:"I like tea.", fa:"من چای دوست دارم.", topic:"علاقه‌ها",
     w:[["I","من"],["like","دوست دارم"],["tea","چای"]]},
    {en:"I love my mother.", fa:"من مادرم را دوست دارم.", topic:"خانواده",
     w:[["I","من"],["love","دوست دارم"],["my","مادرم"],["mother","مادر"]]},
    {en:"She is my sister.", fa:"او خواهر من است.", topic:"خانواده",
     w:[["She","او"],["is","است"],["my","من"],["sister","خواهر"]]},
    {en:"He is my brother.", fa:"او برادر من است.", topic:"خانواده",
     w:[["He","او"],["is","است"],["my","من"],["brother","برادر"]]},
    {en:"The sky is blue.", fa:"آسمان آبی است.", topic:"طبیعت",
     w:[["The","-"],["sky","آسمان"],["is","است"],["blue","آبی"]]},
    {en:"The sun is hot.", fa:"خورشید داغ است.", topic:"طبیعت",
     w:[["The","-"],["sun","خورشید"],["is","است"],["hot","داغ"]]},
    {en:"I drink water.", fa:"من آب می‌نوشم.", topic:"روزمره",
     w:[["I","من"],["drink","می‌نوشم"],["water","آب"]]},
    {en:"I eat bread.", fa:"من نان می‌خورم.", topic:"روزمره",
     w:[["I","من"],["eat","می‌خورم"],["bread","نان"]]},
    {en:"I go to school.", fa:"من به مدرسه می‌روم.", topic:"مدرسه",
     w:[["I","من"],["go","می‌روم"],["to","به"],["school","مدرسه"]]},
    {en:"I read a book.", fa:"من کتاب می‌خوانم.", topic:"مدرسه",
     w:[["I","من"],["read","می‌خوانم"],["a","یک"],["book","کتاب"]]},
    {en:"It is morning.", fa:"صبح است.", topic:"زمان",
     w:[["It","-"],["is","است"],["morning","صبح"]]},
    {en:"It is night.", fa:"شب است.", topic:"زمان",
     w:[["It","-"],["is","است"],["night","شب"]]},
    {en:"Good morning!", fa:"صبح بخیر!", topic:"احوالپرسی",
     w:[["Good","-"],["morning","صبح بخیر"]]},
    {en:"Good night!", fa:"شب بخیر!", topic:"احوالپرسی",
     w:[["Good","-"],["night","شب بخیر"]]},
    {en:"Thank you!", fa:"ممنونم!", topic:"احوالپرسی",
     w:[["Thank","تشکر"],["you","از شما"]]},
    {en:"See you later!", fa:"بعداً می‌بینمت!", topic:"احوالپرسی",
     w:[["See","می‌بینم"],["you","تو را"],["later","بعداً"]]},
    {en:"I have a pen.", fa:"من یک خودکار دارم.", topic:"مدرسه",
     w:[["I","من"],["have","دارم"],["a","یک"],["pen","خودکار"]]},
    {en:"You have a book.", fa:"تو یک کتاب داری.", topic:"مدرسه",
     w:[["You","تو"],["have","داری"],["a","یک"],["book","کتاب"]]},
    {en:"The cat is small.", fa:"گربه کوچک است.", topic:"حیوانات",
     w:[["The","-"],["cat","گربه"],["is","است"],["small","کوچک"]]},
    {en:"The dog is big.", fa:"سگ بزرگ است.", topic:"حیوانات",
     w:[["The","-"],["dog","سگ"],["is","است"],["big","بزرگ"]]},
    {en:"I like apples.", fa:"من سیب دوست دارم.", topic:"غذا",
     w:[["I","من"],["like","دوست دارم"],["apples","سیب"]]},
    {en:"Milk is white.", fa:"شیر سفید است.", topic:"غذا",
     w:[["Milk","شیر"],["is","است"],["white","سفید"]]},
    {en:"I am ten years old.", fa:"من ده سالمه.", topic:"معرفی",
     w:[["I","من"],["am","هستم"],["ten","ده"],["years","سال"],["old","سن"]]},
    {en:"I am from Iran.", fa:"من اهل ایرانم.", topic:"معرفی",
     w:[["I","من"],["am","هستم"],["from","اهل"],["Iran","ایران"]]},
    {en:"I speak Persian.", fa:"من فارسی حرف می‌زنم.", topic:"معرفی",
     w:[["I","من"],["speak","حرف می‌زنم"],["Persian","فارسی"]]},
    {en:"I learn English.", fa:"من انگلیسی یاد می‌گیرم.", topic:"معرفی",
     w:[["I","من"],["learn","یاد می‌گیرم"],["English","انگلیسی"]]}
  ]
},
{
  id: 3, name: "سطح ۳: مکالمه روزمره (A1)", icon: "🗣️",
  desc: "جمله‌هایی که توی زندگی واقعی هر روز لازم داری.",
  tip: "نکته: s سوم شخص رو فراموش نکن: He goes (او می‌رود).",
  kind: "sentence",
  items: [
    {en:"Hello, how are you?", fa:"سلام، حالت چطوره؟", topic:"احوالپرسی",
     w:[["Hello","سلام"],["how","چطور"],["are","هستی"],["you","تو"]]},
    {en:"I am fine, thank you.", fa:"خوبم، ممنون.", topic:"احوالپرسی",
     w:[["I","من"],["am","هستم"],["fine","خوب"],["thank","ممنون"],["you","ازت"]]},
    {en:"What is your name?", fa:"اسمت چیه؟", topic:"آشنایی",
     w:[["What","چه"],["is","است"],["your","تو"],["name","اسم"]]},
    {en:"My name is Sara.", fa:"اسم من ساراست.", topic:"آشنایی",
     w:[["My","من"],["name","اسم"],["is","است"],["Sara","سارا"]]},
    {en:"Where are you from?", fa:"اهل کجایی؟", topic:"آشنایی",
     w:[["Where","کجا"],["are","هستی"],["you","تو"],["from","اهل"]]},
    {en:"Nice to meet you.", fa:"از آشناییت خوشحالم.", topic:"آشنایی",
     w:[["Nice","خوشحال"],["to","از"],["meet","دیدار"],["you","تو"]]},
    {en:"I wake up at seven.", fa:"من ساعت هفت بیدار می‌شم.", topic:"برنامه روزانه",
     w:[["I","من"],["wake","بیدار"],["up","می‌شم"],["at","در"],["seven","هفت"]]},
    {en:"I eat breakfast at eight.", fa:"ساعت هشت صبحانه می‌خورم.", topic:"برنامه روزانه",
     w:[["I","من"],["eat","می‌خورم"],["breakfast","صبحانه"],["at","در"],["eight","هشت"]]},
    {en:"I go to work by bus.", fa:"با اتوبوس می‌رم سر کار.", topic:"رفت‌وآمد",
     w:[["I","من"],["go","می‌رم"],["to","به"],["work","کار"],["by","با"],["bus","اتوبوس"]]},
    {en:"The bus is late today.", fa:"اتوبوس امروز دیر کرده.", topic:"رفت‌وآمد",
     w:[["The","-"],["bus","اتوبوس"],["is","-"],["late","دیر"],["today","امروز"]]},
    {en:"How much is this?", fa:"این چنده؟", topic:"خرید",
     w:[["How","چقدر"],["much","-"],["is","است"],["this","این"]]},
    {en:"It is too expensive.", fa:"خیلی گرونه.", topic:"خرید",
     w:[["It","این"],["is","-"],["too","خیلی"],["expensive","گران"]]},
    {en:"I want to buy a shirt.", fa:"می‌خوام یه پیراهن بخرم.", topic:"خرید",
     w:[["I","من"],["want","می‌خوام"],["to","-"],["buy","بخرم"],["a","یک"],["shirt","پیراهن"]]},
    {en:"Do you have a bigger size?", fa:"سایز بزرگ‌تر داری؟", topic:"خرید",
     w:[["Do","آیا"],["you","شما"],["have","داری"],["a","یک"],["bigger","بزرگ‌تر"],["size","سایز"]]},
    {en:"What time is it?", fa:"ساعت چنده؟", topic:"زمان",
     w:[["What","چه"],["time","ساعت"],["is","است"],["it","-"]]},
    {en:"It is half past three.", fa:"ساعت سه و نیمه.", topic:"زمان",
     w:[["It","-"],["is","است"],["half","نیم"],["past","گذشته"],["three","سه"]]},
    {en:"I am hungry.", fa:"گرسنه‌ام.", topic:"غذا",
     w:[["I","من"],["am","هستم"],["hungry","گرسنه"]]},
    {en:"The food is delicious.", fa:"غذا خوشمزه‌ست.", topic:"غذا",
     w:[["The","-"],["food","غذا"],["is","است"],["delicious","خوشمزه"]]},
    {en:"I would like some tea.", fa:"یه کم چای می‌خوام.", topic:"غذا",
     w:[["I","من"],["would","می‌خوام"],["like","-"],["some","کمی"],["tea","چای"]]},
    {en:"Where is the bathroom?", fa:"دستشویی کجاست؟", topic:"سفر",
     w:[["Where","کجاست"],["is","-"],["the","-"],["bathroom","دستشویی"]]},
    {en:"I need help, please.", fa:"لطفاً کمک لازم دارم.", topic:"سفر",
     w:[["I","من"],["need","لازم دارم"],["help","کمک"],["please","لطفاً"]]},
    {en:"Can you speak slowly?", fa:"می‌شه آروم‌تر حرف بزنی؟", topic:"مکالمه",
     w:[["Can","می‌تونی"],["you","تو"],["speak","حرف بزنی"],["slowly","آروم"]]},
    {en:"I do not understand.", fa:"نمی‌فهمم.", topic:"مکالمه",
     w:[["I","من"],["do","-"],["not","نه"],["understand","می‌فهمم"]]},
    {en:"Please say it again.", fa:"لطفاً دوباره بگو.", topic:"مکالمه",
     w:[["Please","لطفاً"],["say","بگو"],["it","رو"],["again","دوباره"]]},
    {en:"Today is a beautiful day.", fa:"امروز روز قشنگیه.", topic:"آب‌وهوا",
     w:[["Today","امروز"],["is","است"],["a","یک"],["beautiful","قشنگ"],["day","روز"]]},
    {en:"It is raining now.", fa:"الان داره بارون می‌باره.", topic:"آب‌وهوا",
     w:[["It","-"],["is","داره"],["raining","بارون می‌باره"],["now","الان"]]},
    {en:"I like cold weather.", fa:"هوای سرد رو دوست دارم.", topic:"آب‌وهوا",
     w:[["I","من"],["like","دوست دارم"],["cold","سرد"],["weather","هوا"]]},
    {en:"My family is small.", fa:"خانواده من کوچیکه.", topic:"خانواده",
     w:[["My","من"],["family","خانواده"],["is","است"],["small","کوچیک"]]},
    {en:"I have two brothers.", fa:"دو تا برادر دارم.", topic:"خانواده",
     w:[["I","من"],["have","دارم"],["two","دو"],["brothers","برادر"]]},
    {en:"We live in Tehran.", fa:"ما در تهران زندگی می‌کنیم.", topic:"خانواده",
     w:[["We","ما"],["live","زندگی می‌کنیم"],["in","در"],["Tehran","تهران"]]},
    {en:"I work in an office.", fa:"تو یه اداره کار می‌کنم.", topic:"کار",
     w:[["I","من"],["work","کار می‌کنم"],["in","در"],["an","یک"],["office","اداره"]]},
    {en:"My job is interesting.", fa:"کارم جالبه.", topic:"کار",
     w:[["My","من"],["job","کار"],["is","است"],["interesting","جالب"]]},
    {en:"I finish work at six.", fa:"ساعت شش کارم تموم می‌شه.", topic:"کار",
     w:[["I","من"],["finish","تموم می‌کنم"],["work","کار"],["at","در"],["six","شش"]]},
    {en:"I watch TV in the evening.", fa:"عصرها تلویزیون می‌بینم.", topic:"سرگرمی",
     w:[["I","من"],["watch","می‌بینم"],["TV","تلویزیون"],["in","در"],["the","-"],["evening","عصر"]]},
    {en:"I like watching football.", fa:"فوتبال دیدن رو دوست دارم.", topic:"سرگرمی",
     w:[["I","من"],["like","دوست دارم"],["watching","دیدن"],["football","فوتبال"]]},
    {en:"Music makes me happy.", fa:"موزیک خوشحالم می‌کنه.", topic:"سرگرمی",
     w:[["Music","موزیک"],["makes","می‌کنه"],["me","من رو"],["happy","خوشحال"]]},
    {en:"I go to bed at eleven.", fa:"ساعت یازده می‌خوابم.", topic:"برنامه روزانه",
     w:[["I","من"],["go","می‌رم"],["to","به"],["bed","تخت"],["at","در"],["eleven","یازده"]]},
    {en:"Good night, sleep well!", fa:"شب بخیر، خوب بخوابی!", topic:"احوالپرسی",
     w:[["Good","-"],["night","شب بخیر"],["sleep","بخوابی"],["well","خوب"]]},
    {en:"See you tomorrow!", fa:"فردا می‌بینمت!", topic:"احوالپرسی",
     w:[["See","می‌بینم"],["you","تو رو"],["tomorrow","فردا"]]},
    {en:"Have a nice day!", fa:"روز خوبی داشته باشی!", topic:"احوالپرسی",
     w:[["Have","داشته باشی"],["a","یک"],["nice","خوب"],["day","روز"]]}
  ]
},
{
  id: 4, name: "سطح ۴: زندگی روزمره (A2)", icon: "🌅",
  desc: "جمله‌های بلندتر: گذشته، آینده و برنامه‌ریزی.",
  tip: "نکته: گذشته بی‌قاعده‌ها: go→went ، eat→ate ، have→had.",
  kind: "sentence",
  items: [
    {en:"I went to the park yesterday.", fa:"دیروز به پارک رفتم.", topic:"گذشته"},
    {en:"We watched a movie last night.", fa:"دیشب فیلم دیدیم.", topic:"گذشته"},
    {en:"She cooked dinner for us.", fa:"او برای ما شام پخت.", topic:"گذشته"},
    {en:"They played football on Friday.", fa:"آن‌ها جمعه فوتبال بازی کردند.", topic:"گذشته"},
    {en:"I bought a new phone last week.", fa:"هفته پیش یه گوشی جدید خریدم.", topic:"گذشته"},
    {en:"He was very tired after work.", fa:"او بعد از کار خیلی خسته بود.", topic:"گذشته"},
    {en:"We had a great time together.", fa:"با هم خیلی خوش گذروندیم.", topic:"گذشته"},
    {en:"I will travel next month.", fa:"ماه آینده سفر می‌کنم.", topic:"آینده"},
    {en:"She is going to study medicine.", fa:"او می‌خواهد پزشکی بخواند.", topic:"آینده"},
    {en:"We are planning a birthday party.", fa:"داریم یه جشن تولد برنامه‌ریزی می‌کنیم.", topic:"آینده"},
    {en:"I am going to learn driving.", fa:"می‌خواهم رانندگی یاد بگیرم.", topic:"آینده"},
    {en:"They will move to a new house.", fa:"آن‌ها به خانه جدیدی اسباب‌کشی می‌کنند.", topic:"آینده"},
    {en:"I usually drink coffee in the morning.", fa:"معمولاً صبح‌ها قهوه می‌نوشم.", topic:"عادت‌ها"},
    {en:"She often reads before sleeping.", fa:"او اغلب قبل از خواب مطالعه می‌کند.", topic:"عادت‌ها"},
    {en:"We sometimes eat out on weekends.", fa:"گاهی آخر هفته‌ها بیرون غذا می‌خوریم.", topic:"عادت‌ها"},
    {en:"He never drinks tea.", fa:"او هرگز چای نمی‌نوشد.", topic:"عادت‌ها"},
    {en:"I have lived here for five years.", fa:"پنج ساله که اینجا زندگی می‌کنم.", topic:"تجربه"},
    {en:"She has visited three countries.", fa:"او از سه کشور دیدن کرده.", topic:"تجربه"},
    {en:"We have known each other since school.", fa:"ما از دوران مدرسه همدیگر را می‌شناسیم.", topic:"تجربه"},
    {en:"I must finish my homework tonight.", fa:"امشب باید تکالیفم را تمام کنم.", topic:"وظیفه"},
    {en:"You should drink more water.", fa:"باید آب بیشتری بنوشی.", topic:"توصیه"},
    {en:"We have to leave early tomorrow.", fa:"فردا باید زود برویم.", topic:"وظیفه"},
    {en:"If it rains, we will stay home.", fa:"اگر باران ببارد، در خانه می‌مانیم.", topic:"شرط"},
    {en:"I will call you when I arrive.", fa:"وقتی رسیدم بهت زنگ می‌زنم.", topic:"شرط"},
    {en:"This restaurant is better than that one.", fa:"این رستوران از آن یکی بهتر است.", topic:"مقایسه"},
    {en:"Tehran is bigger than Isfahan.", fa:"تهران از اصفهان بزرگ‌تر است.", topic:"مقایسه"},
    {en:"English is easier than I thought.", fa:"انگلیسی از چیزی که فکر می‌کردم راحت‌تر است.", topic:"مقایسه"},
    {en:"She is the tallest girl in class.", fa:"او بلندقدترین دختر کلاس است.", topic:"مقایسه"},
    {en:"I am interested in photography.", fa:"به عکاسی علاقه دارم.", topic:"علاقه"},
    {en:"He is good at playing chess.", fa:"او در شطرنج خوب است.", topic:"مهارت"}
  ]
},
{
  id: 5, name: "سطح ۵: داستان و نظر (B1)", icon: "📖",
  desc: "جمله‌های بلند و طبیعی؛ برای اینکه واقعاً روان بشی.",
  tip: "نکته: حال کامل برای تجربه: I have visited (دیدن کرده‌ام).",
  kind: "sentence",
  items: [
    {en:"Learning a new language opens many doors.", fa:"یادگیری یک زبان جدید درهای زیادی را باز می‌کند.", topic:"انگیزشی"},
    {en:"Practice a little every day and you will improve.", fa:"هر روز کمی تمرین کن و پیشرفت می‌کنی.", topic:"انگیزشی"},
    {en:"Do not be afraid of making mistakes.", fa:"از اشتباه کردن نترس.", topic:"انگیزشی"},
    {en:"The more you listen, the better you understand.", fa:"هر چه بیشتر گوش بدهی، بهتر می‌فهمی.", topic:"انگیزشی"},
    {en:"Once upon a time, there was a small village.", fa:"روزی روزگاری، روستای کوچکی بود.", topic:"داستان"},
    {en:"The old man told stories every evening.", fa:"پیرمرد هر عصر داستان تعریف می‌کرد.", topic:"داستان"},
    {en:"Suddenly, the lights went out.", fa:"ناگهان چراغ‌ها خاموش شدند.", topic:"داستان"},
    {en:"They walked for hours through the forest.", fa:"آن‌ها ساعت‌ها در جنگل راه رفتند.", topic:"داستان"},
    {en:"In my opinion, traveling is the best teacher.", fa:"به نظر من، سفر بهترین معلم است.", topic:"نظر"},
    {en:"I believe technology makes life easier.", fa:"معتقدم تکنولوژی زندگی را راحت‌تر می‌کند.", topic:"نظر"},
    {en:"It seems to me that books never get old.", fa:"به نظرم کتاب‌ها هرگز قدیمی نمی‌شوند.", topic:"نظر"},
    {en:"The weather today is perfect for a walk.", fa:"هوای امروز برای پیاده‌روی عالی است.", topic:"روزمره"},
    {en:"I spent the whole afternoon cleaning my room.", fa:"کل بعدازظهر را صرف تمیز کردن اتاقم کردم.", topic:"روزمره"},
    {en:"She explained the problem very clearly.", fa:"او مشکل را خیلی واضح توضیح داد.", topic:"کار"},
    {en:"We need to make a decision soon.", fa:"باید به‌زودی تصمیم بگیریم.", topic:"کار"},
    {en:"He apologized for being late.", fa:"او به خاطر دیر آمدن عذرخواهی کرد.", topic:"اجتماعی"},
    {en:"They invited us to their wedding.", fa:"آن‌ها ما را به عروسی‌شان دعوت کردند.", topic:"اجتماعی"},
    {en:"I ran into an old friend at the mall.", fa:"توی مرکز خرید یه دوست قدیمی رو دیدم.", topic:"اجتماعی"},
    {en:"Could you please open the window?", fa:"میشه لطفاً پنجره رو باز کنی؟", topic:"مؤدبانه"},
    {en:"Would you mind helping me with this?", fa:"اشکالی نداره تو این کار کمکم کنی؟", topic:"مؤدبانه"},
    {en:"I am looking forward to seeing you.", fa:"مشتاقانه منتظر دیدنت هستم.", topic:"مؤدبانه"},
    {en:"Despite the rain, we enjoyed the trip.", fa:"با وجود باران، از سفر لذت بردیم.", topic:"پیشرفته"},
    {en:"He succeeded because he never gave up.", fa:"او موفق شد چون هرگز تسلیم نشد.", topic:"پیشرفته"},
    {en:"Reading books improves your vocabulary a lot.", fa:"کتاب خواندن دایره لغتت را خیلی زیاد می‌کند.", topic:"یادگیری"}
  ]
},
{
  id: 6, name: "تمرکز فارسی 🎯", icon: "🎯",
  desc: "صداهایی که برای فارسی‌زبانان سختن: th، w/v، ship/sheep و...",
  kind: "word",
  tip: "نکته: صدای th رو با نوک زبون بین دندون‌ها بگو: think نه sink!",
  items: [
    {en:"think", fa:"فکر کردن — th نوک‌زبانی، نه «سینک»!", topic:"صدای th"},
    {en:"thank", fa:"تشکر — th مثل think", topic:"صدای th"},
    {en:"three", fa:"سه — th، نه «تری»!", topic:"صدای th"},
    {en:"this", fa:"این — th صدادار", topic:"صدای th"},
    {en:"that", fa:"آن — th صدادار", topic:"صدای th"},
    {en:"they", fa:"آن‌ها — th صدادار", topic:"صدای th"},
    {en:"west", fa:"غرب — w با لب گرد، نه «وِست»!", topic:"w در برابر v"},
    {en:"wine", fa:"شراب — w، نه v!", topic:"w در برابر v"},
    {en:"wet", fa:"خیس — w", topic:"w در برابر v"},
    {en:"very", fa:"خیلی — v با دندون روی لب", topic:"w در برابر v"},
    {en:"voice", fa:"صدا — v", topic:"w در برابر v"},
    {en:"seven", fa:"هفت — v وسط کلمه", topic:"w در برابر v"},
    {en:"ship", fa:"کشتی — i کوتاه", topic:"i کوتاه/بلند"},
    {en:"sheep", fa:"گوسفند — ee کشیده", topic:"i کوتاه/بلند"},
    {en:"chip", fa:"چیپس — i کوتاه", topic:"i کوتاه/بلند"},
    {en:"cheap", fa:"ارزان — ea کشیده", topic:"i کوتاه/بلند"},
    {en:"street", fa:"خیابان — خوشه st بدون مصوت اضافه!", topic:"خوشه‌های همخوان"},
    {en:"splash", fa:"پاشیدن — خوشه spl", topic:"خوشه‌های همخوان"},
    {en:"spring", fa:"بهار — خوشه spr", topic:"خوشه‌های همخوان"},
    {en:"bring", fa:"آوردن — ng بدون «گ» اضافه!", topic:"صدای ng"},
    {en:"sing", fa:"آواز خواندن — ng", topic:"صدای ng"},
    {en:"morning", fa:"صبح — ng", topic:"صدای ng"}
  ]
}
];
